CONFIG_DEBUG=n
CONFIG_GPIO=y
CONFIG_FLASH_BASE_ADDRESS=0x30200
CONFIG_FLASH_LOAD_OFFSET=0x00

# # disable log
# CONFIG_LOG=n
# CONFIG_PRINTK=n
# CONFIG_BOOT_BANNER=n

# enable log
CONFIG_LOG=y
#CONFIG_SERIAL=y
#CONFIG_UART_CONSOLE=y
#CONFIG_LOG_BACKED_UART=y
#CONFIG_LOG_DEFAULT_LEVEL=4
#CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_MODE_DEFERRED=y
#CONFIG_LOG_PRINTK=y
CONFIG_PRINTK=y
CONFIG_BOOT_BANNER=y

CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE=16384

CONFIG_MAIN_STACK_SIZE=32768
CONFIG_HEAP_MEM_POOL_SIZE=131072

CONFIG_LED=y


#CONFIG_SYSTEM_TIMER=y
#CONFIG_SYS_CLOCK_EXISTS=y
#CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_VID=0x4170
CONFIG_USB_DEVICE_PID=0x2007
CONFIG_USB_DEVICE_MANUFACTURER="HITO"
CONFIG_USB_DEVICE_PRODUCT="hito.root"

CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=n
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Hito"
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_HCI_ACL_FLOW_CONTROL=y
CONFIG_BT_RPMSG=y
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_GATT_SERVICE_CHANGED=y
CONFIG_BT_L2CAP_TX_MTU=514
CONFIG_BT_BUF_ACL_RX_SIZE=514

CONFIG_BT_THROUGHPUT=n
CONFIG_BT_USER_PHY_UPDATE=y
#CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_USER_DATA_LEN_UPDATE=y

#CONFIG_BT_CTLR=n

CONFIG_PM=y
CONFIG_PM_DEVICE=y
#CONFIG_PM_SINGLE_IMAGE=n
#CONFIG_PM_PARTITION_SIZE_SETTINGS_STORAGE=0x1000


CONFIG_I2C=y
CONFIG_SPI=y

CONFIG_PWM=y        # for brightness control of LCD

CONFIG_LED=y        # LED support
CONFIG_LED_PWM=y
