CONFIG_DEBUG=n
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_PRINTK=y
CONFIG_BOOT_BANNER=y
CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE=16384
CONFIG_MAIN_STACK_SIZE=32768
CONFIG_HEAP_MEM_POOL_SIZE=163840
CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_PWM=y
CONFIG_LED=y
CONFIG_LED_PWM=y
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Hito devboard"
CONFIG_BT_HCI_ACL_FLOW_CONTROL=y
CONFIG_BT_RPMSG=y
CONFIG_BT_L2CAP_TX_MTU=514
CONFIG_BT_BUF_ACL_RX_SIZE=514
CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_USER_DATA_LEN_UPDATE=y
