# Find the actual Cargo dependency, including local [patch] overrides.
if(NOT HITO_CARGO_MANIFEST)
  set(HITO_CARGO_MANIFEST "${CMAKE_CURRENT_SOURCE_DIR}/Cargo.toml")
endif()
if(DEFINED ENV{CARGO} AND NOT "$ENV{CARGO}" STREQUAL "")
  set(HITO_CARGO "$ENV{CARGO}")
else()
  find_program(HITO_CARGO cargo REQUIRED)
endif()
execute_process(COMMAND "${HITO_CARGO}" metadata --format-version 1 --manifest-path "${HITO_CARGO_MANIFEST}"
  RESULT_VARIABLE result OUTPUT_VARIABLE metadata ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Could not resolve hito_core with Cargo: ${error}")
endif()
string(JSON count LENGTH "${metadata}" packages)
math(EXPR last "${count} - 1")
set(HITO_CORE_MATCHES)
foreach(index RANGE ${last})
  string(JSON name GET "${metadata}" packages ${index} name)
  if(name STREQUAL "hito_core")
    string(JSON manifest GET "${metadata}" packages ${index} manifest_path)
    get_filename_component(directory "${manifest}" DIRECTORY)
    list(APPEND HITO_CORE_MATCHES "${directory}")
  endif()
endforeach()
list(LENGTH HITO_CORE_MATCHES count)
if(NOT count EQUAL 1)
  message(FATAL_ERROR "Expected one hito_core dependency, found ${count}; align its Git revision across all consumers")
endif()
list(GET HITO_CORE_MATCHES 0 HITO_CORE_DIR)
include("${HITO_CORE_DIR}/cmake/platform.cmake")
